# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Dependabot configuration for updating dependencies and GitHub Actions
version: 2 # Specifies the version of the Dependabot configuration schema

updates:
  # Configuration for Python package updates using pip
- package-ecosystem: pip   # Specifies that the dependency ecosystem is pip (Python package manager)
  directory: /   # The directory where the dependencies are located (root directory in this case)
  schedule:
    interval: monthly   # Updates will be scheduled to run once a month
  open-pull-requests-limit: 5   # Limits the number of open pull requests to 5
  groups:   # Groups configuration for dependency updates
    production-dependencies:
      dependency-type: production   # Updates for production dependencies
    development-dependencies:
      dependency-type: development   # Updates for development dependencies

  # Configuration for GitHub Actions updates
- package-ecosystem: github-actions   # Specifies that the dependency ecosystem is GitHub Actions
  directory: /   # The directory where GitHub Actions workflows are located (root directory in this case)
  schedule:
    interval: monthly   # Updates will be scheduled to run once a month
  open-pull-requests-limit: 5   # Limits the number of open pull requests to 5
